meta_product_name: "Le clos Valliere"
meta_title: "Le clos Valliere - Gîte en plein coeur de la Touraine"
meta_description: "Gîte hotellier composé de deux parties. Mariage, fêtes en tous genres, réunions, parfait dans tous les câdres."
meta_image: "jardin1.jpg" # should exist in `app/assets/images/`
