# development:
#   :concurrency: 5

# production:
#   :concurrency: 10

# :max_retries: 1

# :queues:
#   - default
# # start the job every first of the month
# base_worker_job:
#   cron: "0 0 1 * *"
#   class: "BaseWorkerJob"
#   queue: default
