name: Ruby
on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
        ruby: ['2.7', '3.0', '3.1', head, jruby, jruby-head, truffleruby, truffleruby-head]
    runs-on: ${{ matrix.os }}
    
    services:
      postgres:
        image: postgres:12
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install PostgreSQL 12 client
      run: |
        sudo apt-get -yqq install libpq-dev
    - name: Cache Ruby Gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Bundle Install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run Tests
      env:
        PG_DATABASE: postgres
        PG_HOST: localhost
        PG_USER: postgres
        PG_PASSWORD: password
        RAILS_ENV: test
        WITH_COVERAGE: true
        DISABLE_SPRING: 1
      run: |
        bin/rails db:setup
        bundle exec rake test
    - name: Upload Code Coverage
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage
        path: coverage/
    - name: Formatting and Security Checks
      run: |
        bundle exec rubocop
        bundle exec brakeman -z
        gem install bundle-audit
        bundle-audit update
        bundle-audit
