# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Ruby
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  runner-job:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports: 
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '3.0.2'
      - name: Install dependent libraries
        run: bundle install
      - name: Run Tests
        env:
          POSTGRES_DATABASE: postgresql
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PORT: 5432
        run: |
          ps ax | grep postgres
          sudo service postgresql restart
          bin/rails db:schema:load
          bundle exec rake test
